trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo Build First Job
    - job: SecondJob
      steps:
      - bash: echo Build Second Job
- stage: DevDeploy
  variables:
    priyanka: priya
  dependsOn: Build
  jobs:
    - job: DevFist
      steps:
      - bash: echo $(priyanka)DeployJob
    - job: DevSeccond
      steps:
      - bash: echo Dev Second Job
- stage: QADeploy
  variables:
     priyanka: 
  dependsOn: Build
  jobs:
    - job: QAJob
      steps:
      - bash: echo $(priyanka)QADeploy
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
    - job: ProductionsJob
      steps:
      - bash: echo $(priyanka)ProdDeploy
